version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test_android:
    docker:
      - image: cimg

    steps:
      - checkout

      - run:
          name: Install React Native & Dependencies
          command: |
            yarn install

      - run:
          name: Run Pre-Build Tests (Jest or similar)
          command: |
            yarn test

      - run:
          name: Build Android App
          command: |
            cd android
            ./gradlew assembleDebug

      - run:
          name: Run Android Instrumentation Tests (Optional)
          command: |
            cd android
            ./gradlew testDebugUnitTest

workflows:
  build_and_test:
    jobs:
      - build_and_test_android
