version: 2.1


jobs:
  build_and_test_android:
    docker:
      - image: cimg/node:18.20.0

    steps:
      - checkout

      - run:
          name: Install Yarn
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt update && sudo apt install -y yarn

      - run:
          name: Install React Native & Dependencies
          command: |
            yarn install

      - run:
          name: Run Pre-Build Tests (Jest or similar)
          command: |
            yarn test

      - run:
          name: Build Android App
          command: |
            cd android
            ./gradlew assembleDebug

      - run:
          name: Run Android Instrumentation Tests (Optional)
          command: |
            cd android
            ./gradlew testDebugUnitTest

workflows:
  build_and_test:
    jobs:
      - build_and_test_android
