version: 2.1


jobs:
  build_and_test_android:
    docker:
      - image: cimg/node:18.20.0

    steps:
      - checkout

      - run:
          name: Configure JAVA_HOME for OpenJDK 17
          command: |
            sudo apt update
            sudo apt install -y openjdk-17-jdk
            export JAVA_HOME="/Users/farhanasim/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk"
            echo 'export JAVA_HOME=/Users/farhanasim/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk' >> $BASH_ENV
            echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            java -version

      - run:
          name: Set ANDROID_HOME and sdk.dir
          command: |
            export ANDROID_HOME=/Users/farhanasim/Library/Android/sdk
            echo 'export ANDROID_HOME=/Users/farhanasim/Library/Android/sdk' >> $BASH_ENV
            echo 'sdk.dir=$ANDROID_HOME' > android/local.properties

      - run:
          name: Install React Native & Dependencies
          command: |
            yarn install

      - run:
          name: Build Android App
          command: |
            yarn android

      - run:
          name: Run Android Instrumentation Tests (Optional)
          command: |
            cd android
            ./gradlew assembleRelease

workflows:
  build_and_test:
    jobs:
      - build_and_test_android
