version: 2.1


jobs:
  build_and_test_android:
    docker:
      - image: cimg/node:18.20.0

    steps:
      - checkout

      - run:
          name: Configure JAVA_HOME for OpenJDK 11
          command: |
            sudo apt update
            sudo apt install -y openjdk-11-jdk
            export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
            echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64' >> $BASH_ENV
            echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            java -version

      - run:
          name: Install React Native & Dependencies
          command: |
            yarn install

      - run:
          name: Build Android App
          command: |
            cd android
            ./gradlew assembleDebug

      - run:
          name: Run Android Instrumentation Tests (Optional)
          command: |
            cd android
            ./gradlew testDebugUnitTest

workflows:
  build_and_test:
    jobs:
      - build_and_test_android
