version: 2.1


jobs:
  build_and_test_android:
    docker:
      - image: cimg/node:18.20.0

    steps:
      - checkout

      - run:
          name: Configure JAVA_HOME and PATH
          command: |
            export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
            echo "export JAVA_HOME=$JAVA_HOME" >> $BASH_ENV
            echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            java -version

      - run:
          name: Install React Native & Dependencies
          command: |
            yarn install

      - run:
          name: Build Android App
          command: |
            cd android
            ./gradlew assembleDebug

      - run:
          name: Run Android Instrumentation Tests (Optional)
          command: |
            cd android
            ./gradlew testDebugUnitTest

workflows:
  build_and_test:
    jobs:
      - build_and_test_android
